# Generated by Django 4.2 on 2026-06-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_alter_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='inactive_reason',
            field=models.CharField(blank=True, choices=[('Freeze', 'Freeze'), ('Left', 'Left'), ('Expelled', 'Expelled'), ('', 'None')], default='', max_length=10),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['course', 'date'], name='idx_attend_course_date'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-date'], name='idx_notif_date_desc'),
        ),
        migrations.AddIndex(
            model_name='payments',
            index=models.Index(fields=['studentsession', 'amount'], name='idx_pay_session_amount'),
        ),
    ]
