# Generated by Django 4.2 on 2026-06-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_decimal_softdelete_latefee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Late Fee', 'Late fee'), ('New Entry', 'New Entry'), ('Deletion', 'Deletion'), ('New Fee', 'New Fee'), ('Updation', 'Updation'), ('Monthly Renewal', 'Monthly Renewal'), ('Payment', 'Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_month',
            field=models.CharField(blank=True, help_text='YYYY-MM key for deduplicating recurring notifications.', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='month',
            field=models.CharField(blank=True, db_index=True, help_text='YYYY-MM that this payment applies to (for monthly sessions / late fee tracking).', max_length=7, null=True),
        ),
    ]
